// user_frontend/src/pages/index.tsx
import Layout from '@/components/Layout';
import Link from 'next/link';

export default function Home() {
  return (
    <Layout title='Home - Menu App'>
      <div className='text-center py-12'>
        <h1 className='text-4xl font-bold text-gray-900 mb-4'>
          メニューアプリへようこそ
        </h1>
        <p className='text-xl text-gray-600 mb-8'>
          レストランのメニューを閲覧できます
        </p>
        <Link
          href='/menus'
          className='inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 transition-colors'
        >
          メニュー一覧を見る
        </Link>
      </div>
    </Layout>
  );
}

// admin_frontend/pages/index.vue
<template>
  <div class="min-h-screen bg-gray-50 flex items-center justify-center">
    <div class="text-center">
      <h1 class="text-4xl font-bold text-gray-900 mb-4">管理画面</h1>
      <p class="text-xl text-gray-600 mb-8">メニュー管理システム</p>
      <NuxtLink
        to="/admin/menus"
        class="inline-block bg-blue-600 text-white px-8 py-3 rounded-md hover:bg-blue-700 transition-colors font-medium"
      >
        メニュー管理へ
      </NuxtLink>
    </div>
  </div>
</template>
